-- 5.
SELECT PUBLISHER
FROM BOOK
WHERE BOOKID IN (SELECT BOOKID
                                      FROM ORDERS
                                      WHERE CUSTID=1);

-- 6.
SELECT CS.NAME, BK.BOOKNAME, BK.PRICE, BK.PRICE - OD.SALEPRICE "차이"
FROM CUSTOMER CS, ORDERS OD, BOOK BK
WHERE CS.CUSTID = OD.CUSTID AND
                OD.BOOKID = BK.BOOKID AND CS.CUSTID = 1;

-- 7.
SELECT BOOKNAME
FROM BOOK
MINUS
SELECT BOOKNAME
FROM BOOK
WHERE BOOKID IN (SELECT BOOKID
                                      FROM ORDERS
                                      WHERE CUSTID=1);

-- 8.
SELECT NAME
FROM CUSTOMER
WHERE CUSTID NOT IN (SELECT CUSTID
                                                FROM ORDERS);

-- 9.
SELECT SUM(SALEPRICE) "주문총액" ,  AVG(SALEPRICE) "주문평균"
FROM ORDERS;

-- 10.
SELECT CUSTID, NAME, (SELECT SUM(SALEPRICE)
                            FROM ORDERS OD
                            WHERE OD.CUSTID = CS.CUSTID) "구매액"
FROM CUSTOMER CS
GROUP BY CUSTID, NAME
ORDER BY CUSTID;

-- 11.
SELECT CS.NAME, BK.BOOKNAME
FROM CUSTOMER CS, ORDERS, BOOK BK
WHERE CS.CUSTID = ORDERS.CUSTID AND
                ORDERS.BOOKID = BK.BOOKID
ORDER BY NAME;

-- 12.
SELECT OD.ORDERID, MAX(BK.PRICE-OD.SALEPRICE) "큰차이"
FROM ORDERS OD, BOOK BK
WHERE OD.BOOKID = BK.BOOKID AND 
                BK.PRICE-OD.SALEPRICE = (SELECT MAX(BK.PRICE-OD.SALEPRICE)  
                                                                    FROM ORDERS OD , BOOK BK 
                                                                    WHERE OD.BOOKID = BK.BOOKID)
GROUP BY  OD.ORDERID;

-- 13.
SELECT CS.NAME, AVG(OD.SALEPRICE)
FROM CUSTOMER CS, ORDERS OD
WHERE CS.CUSTID = OD.CUSTID
GROUP BY CS.NAME
HAVING AVG(OD.SALEPRICE) > (SELECT AVG(SALEPRICE) FROM ORDERS);
