SELECT *
FROM BOOK
WHERE BOOKNAME LIKE '%축구%';

-- 뷰 생성
CREATE VIEW VW_BOOK
AS SELECT *
FROM BOOK
WHERE BOOKNAME LIKE '%축구%';

-- 뷰 테이블 확인
SELECT *
FROM VW_BOOK;

-- 뷰 테이블 삭제
DROP VIEW VW_ORDER;

-- 없으면 생성, 있으면 업데이트(수정)
CREATE OR REPLACE VIEW VW_ORDER(ORDERID, CUSTID, NAME, BOOKID, BOOKNAME, SALEPRICE, ORDERDATE)
AS SELECT OD.ORDERID, OD.CUSTID, CS.NAME, OD.BOOKID, BK.BOOKNAME, OD.SALEPRICE, OD.ORDERDATE
FROM ORDERS OD, CUSTOMER CS, BOOK BK
WHERE OD.CUSTID = CS.CUSTID AND OD.BOOKID = BK.BOOKID
ORDER BY OD.ORDERID;

-- 사용 예시
SELECT ORDERID, BOOKNAME, SALEPRICE
FROM VW_ORDER
WHERE NAME = '김연아';