SELECT (SELECT NAME 
                FROM CUSTOMER CS 
                WHERE CS.CUSTID = OD.CUSTID) "NAME", SUM(SALEPRICE) "TOTAL"
FROM ORDERS OD
GROUP BY OD.CUSTID;

SELECT NAME, SUM(SALEPRICE)
FROM ORDERS OD, CUSTOMER CS
WHERE OD.CUSTID = CS.CUSTID
GROUP BY NAME;

---
SELECT CS.NAME, SUM(OD.SALEPRICE) "TOTAL"
FROM (SELECT CUSTID, NAME
            FROM CUSTOMER
            WHERE CUSTID <=2) CS, ORDERS OD
WHERE CS.CUSTID = OD.CUSTID
GROUP BY CS.NAME;

---
-- 1. 비상관 서브 질의
SELECT ORDERID, SALEPRICE
FROM ORDERS
WHERE SALEPRICE <= (SELECT AVG(SALEPRICE)
                                            FROM ORDERS);

-- 2. 상관 서브 질의
SELECT ORDERID, CUSTID, SALEPRICE
FROM ORDERS OD
WHERE SALEPRICE > (SELECT AVG(SALEPRICE)
                                            FROM ORDERS SOD
                                            WHERE OD.CUSTID = SOD.CUSTID);
---
SELECT SUM(SALEPRICE) "TOTAL"
FROM ORDERS
WHERE CUSTID IN (SELECT CUSTID
                                FROM CUSTOMER
                                WHERE ADDRESS LIKE '%대한민국%');
---
SELECT ORDERID, SALEPRICE
FROM ORDERS
WHERE SALEPRICE > ALL (SELECT SALEPRICE FROM ORDERS WHERE CUSTID = 3);

---
SELECT SUM(SALEPRICE) "TOTAL"
FROM ORDERS OD
WHERE EXISTS (SELECT *
                            FROM CUSTOMER CS
                            WHERE ADDRESS LIKE '%대한민국%' AND CS.CUSTID = OD.CUSTID);


