-- ¿¬½À ¹®Á¦
SELECT BOOKNAME FROM BOOK WHERE BOOKID = 1;
SELECT BOOKNAME FROM BOOK WHERE PRICE >= 20000;
SELECT SUM(SALEPRICE) FROM ORDERS WHERE CUSTID = 1;
SELECT COUNT(*) FROM ORDERS WHERE CUSTID =1;

SELECT COUNT(*) FROM BOOK;
SELECT PUBLISHER, COUNT(*) FROM BOOK GROUP BY PUBLISHER;
SELECT NAME, ADDRESS FROM CUSTOMER;
SELECT BOOKID FROM ORDERS WHERE ORDERDATE BETWEEN '2014/07/04' AND '2014/07/07' GROUP BY BOOKID;
SELECT BOOKID FROM ORDERS WHERE ORDERDATE NOT BETWEEN '2014/07/04' AND '2014/07/07' GROUP BY BOOKID;
SELECT NAME, ADDRESS FROM CUSTOMER WHERE NAME LIKE '±è%';
SELECT NAME, ADDRESS FROM CUSTOMER WHERE NAME LIKE '±è%¾Æ';