CREATE INDEX IX_BOOK ON BOOK(BOOKNAME);
CREATE INDEX IX_BOOK2 ON BOOK(PUBLISHER, PRICE);

DROP INDEX IX_BOOK;
DROP INDEX IX_BOOK2;

-- 실제 인덱스 생성후 COST가 줄어들었다. (자동추적에서 확인 가능)
SELECT *
FROM BOOK
WHERE PUBLISHER = '대한미디어' AND PRICE >= 30000;